import type { NewsCategory } from "./types";

export const categoryGlyphs: Record<NewsCategory, string> = {
  Technology: "🤖",
  Nature: "🌿",
  Culture: "🎵",
  Science: "🔬",
  Business: "💼",
  Environment: "🌍",
  Art: "🎨",
  Education: "📚",
  Weather: "✨",
  Media: "📰",
  Food: "🍽️",
  Sports: "⚽",
  History: "🏛️",
  Transport: "🚆",
  Ocean: "⛵",
  Health: "🏥",
  Politics: "🌐",
  Other: "📋",
};

export const categoryColors: Record<NewsCategory, string> = {
  Technology: "bg-cyan-200",
  Nature: "bg-lime-200",
  Culture: "bg-pink-200",
  Science: "bg-sky-200",
  Business: "bg-violet-200",
  Environment: "bg-emerald-200",
  Art: "bg-rose-200",
  Education: "bg-indigo-200",
  Weather: "bg-slate-200",
  Media: "bg-blue-200",
  Food: "bg-orange-200",
  Sports: "bg-yellow-200",
  History: "bg-stone-200",
  Transport: "bg-teal-200",
  Ocean: "bg-blue-100",
  Health: "bg-green-200",
  Politics: "bg-purple-200",
  Other: "bg-gray-200",
};

export const categoryGradients: Record<NewsCategory, string> = {
  Technology: "from-cyan-200 via-white to-pink-200",
  Nature: "from-sky-200 via-white to-lime-200",
  Culture: "from-pink-200 via-white to-violet-200",
  Science: "from-emerald-200 via-white to-cyan-200",
  Business: "from-yellow-200 via-white to-violet-200",
  Environment: "from-lime-200 via-white to-orange-200",
  Art: "from-rose-200 via-white to-indigo-200",
  Education: "from-indigo-200 via-white to-slate-200",
  Weather: "from-teal-200 via-white to-purple-200",
  Media: "from-blue-200 via-white to-rose-200",
  Food: "from-orange-200 via-white to-lime-200",
  Sports: "from-yellow-200 via-white to-green-200",
  History: "from-amber-200 via-white to-stone-200",
  Transport: "from-teal-200 via-white to-orange-200",
  Ocean: "from-cyan-200 via-white to-blue-200",
  Health: "from-green-200 via-white to-teal-200",
  Politics: "from-purple-200 via-white to-blue-200",
  Other: "from-gray-200 via-white to-slate-200",
};

// Guardian API section → NewsCategory
export const guardianSectionToCategory: Record<string, NewsCategory> = {
  world: "Politics",
  "us-news": "Politics",
  "uk-news": "Politics",
  politics: "Politics",
  technology: "Technology",
  science: "Science",
  environment: "Environment",
  sport: "Sports",
  football: "Sports",
  culture: "Culture",
  arts: "Art",
  music: "Art",
  film: "Art",
  "food-and-drink": "Food",
  travel: "Nature",
  business: "Business",
  education: "Education",
  media: "Media",
  health: "Health",
  society: "Other",
  lifeandstyle: "Culture",
  commentisfree: "Media",
  weather: "Weather",
};
