import type { NewsItem } from "./types";

export const sampleNews: NewsItem[] = [
  {
    id: "sample-1",
    city: "東京",
    country: "日本",
    category: "Technology",
    title: "学生制作ロボットが集まるフェスティバル開幕",
    summary:
      "次世代のものづくりを担う学校や地域チームの作品が展示されています。来場者は実際に触れて体験できます。",
    timeZone: "Asia/Tokyo",
    gradient: "from-cyan-200 via-white to-pink-200",
    glyph: "🤖",
  },
  {
    id: "sample-2",
    city: "シドニー",
    country: "オーストラリア",
    category: "Nature",
    title: "海岸清掃イベントに過去最多の参加者",
    summary:
      "市民団体と学生ボランティアが協力し、海辺の環境保全に取り組みました。回収したごみは統計データとして活用されます。",
    timeZone: "Australia/Sydney",
    gradient: "from-sky-200 via-white to-lime-200",
    glyph: "🌊",
  },
  {
    id: "sample-3",
    city: "ソウル",
    country: "韓国",
    category: "Culture",
    title: "夜市で音楽と屋台文化を楽しむイベント",
    summary:
      "地域アーティストの演奏と、地域の食文化を紹介する小さな祭りが開かれました。",
    timeZone: "Asia/Seoul",
    gradient: "from-pink-200 via-white to-violet-200",
    glyph: "🎵",
  },
  {
    id: "sample-4",
    city: "シンガポール",
    country: "シンガポール",
    category: "Science",
    title: "都市型グリーン行の気温を下げる研究結果",
    summary:
      "緑化エリアや歩行者空間の快適さに与える影響を調べた実験が行われました。",
    timeZone: "Asia/Singapore",
    gradient: "from-emerald-200 via-white to-cyan-200",
    glyph: "🔬",
  },
  {
    id: "sample-5",
    city: "ドバイ",
    country: "UAE",
    category: "Business",
    title: "交通拠点で太陽光発電の拡大計画",
    summary:
      "公共施設の電力利用を見直し、再生可能エネルギーの割合を高める予定です。",
    timeZone: "Asia/Dubai",
    gradient: "from-yellow-200 via-white to-violet-200",
    glyph: "☀️",
  },
  {
    id: "sample-6",
    city: "ナイロビ",
    country: "ケニア",
    category: "Environment",
    title: "野生動物の移動ルートを可視化した新地図",
    summary:
      "研究者たちは保護区のデータをもとに、動物たちの移動傾向を分析しました。",
    timeZone: "Africa/Nairobi",
    gradient: "from-lime-200 via-white to-orange-200",
    glyph: "🦁",
  },
  {
    id: "sample-7",
    city: "パリ",
    country: "フランス",
    category: "Art",
    title: "美術館で光を使った体験型展示が開始",
    summary:
      "来場者の動きに合わせて変化する映像作品が注目を集めています。",
    timeZone: "Europe/Paris",
    gradient: "from-rose-200 via-white to-indigo-200",
    glyph: "🎨",
  },
  {
    id: "sample-8",
    city: "ロンドン",
    country: "イギリス",
    category: "Education",
    title: "図書館の週末プログラミング講座を拡大",
    summary:
      "初心者向けのワークショップが増え、若い参加者が学びやすくなっています。",
    timeZone: "Europe/London",
    gradient: "from-indigo-200 via-white to-slate-200",
    glyph: "📚",
  },
  {
    id: "sample-9",
    city: "レイキャビク",
    country: "アイスランド",
    category: "Weather",
    title: "オーロラ予報で北部海岸への観光客が増加",
    summary:
      "天候が安定した週末に向けて、観測スポットの案内が強化されています。",
    timeZone: "Atlantic/Reykjavik",
    gradient: "from-teal-200 via-white to-purple-200",
    glyph: "✨",
  },
  {
    id: "sample-10",
    city: "ニューヨーク",
    country: "アメリカ",
    category: "Media",
    title: "地域ニュースルームに若い記者がスカウトへ",
    summary:
      "学生記者が地域の話題を発信する新しい取り組みが始まりました。",
    timeZone: "America/New_York",
    gradient: "from-blue-200 via-white to-rose-200",
    glyph: "📰",
  },
  {
    id: "sample-11",
    city: "メキシコシティ",
    country: "メキシコ",
    category: "Food",
    title: "歴史地区でストリートフードフェア開催",
    summary:
      "伝統料理と新しいアレンジを紹介する屋台が並び、多くの人が訪れました。",
    timeZone: "America/Mexico_City",
    gradient: "from-orange-200 via-white to-lime-200",
    glyph: "🍽️",
  },
  {
    id: "sample-12",
    city: "サンパウロ",
    country: "ブラジル",
    category: "Sports",
    title: "ユースサッカーリーグが決勝ラウンドへ",
    summary:
      "地域チームが集まり、週末に市内大会の最終戦が行われます。",
    timeZone: "America/Sao_Paulo",
    gradient: "from-yellow-200 via-white to-green-200",
    glyph: "⚽",
  },
  {
    id: "sample-13",
    city: "バンクーバー",
    country: "カナダ",
    category: "Nature",
    title: "山道の修復プロジェクトが最終段階に",
    summary:
      "利用者の安全と自然環境の保護を両立させるため、整備計画が整いました。",
    timeZone: "America/Vancouver",
    gradient: "from-green-200 via-white to-sky-200",
    glyph: "🌿",
  },
  {
    id: "sample-14",
    city: "カイロ",
    country: "エジプト",
    category: "History",
    title: "古い都市並みをデジタル化するアーカイブ計画",
    summary:
      "歴史的な街並みを記録した資料をオンラインで見られる形に整備しています。",
    timeZone: "Africa/Cairo",
    gradient: "from-amber-200 via-white to-stone-200",
    glyph: "🏛️",
  },
  {
    id: "sample-15",
    city: "ムンバイ",
    country: "インド",
    category: "Transport",
    title: "駅で混雑解消システムの実証実験",
    summary:
      "人の流れをリアルタイムで表示し、移動のスムーズさを改善する試みです。",
    timeZone: "Asia/Kolkata",
    gradient: "from-teal-200 via-white to-orange-200",
    glyph: "🚆",
  },
  {
    id: "sample-16",
    city: "ケープタウン",
    country: "南アフリカ",
    category: "Ocean",
    title: "港でクリーン船舶の地域実験",
    summary:
      "海洋環境への負荷を減らすため、港湾チームが新しい運用方法を試しています。",
    timeZone: "Africa/Johannesburg",
    gradient: "from-cyan-200 via-white to-blue-200",
    glyph: "⛵",
  },
];
